### ISSUE TITLE
Not displaying suggestions within Bootstrap offcanvas on Firefox

### ISSUE THREAD

**Issue by AlonsoK28** [digitalfortress-tech/typeahead-standalone#47]
### What happened?

The component is not displayed into Firefox browser (lastest)

![image](https://user-images.githubusercontent.com/37458700/218941765-023fddef-dc6b-45f6-8a90-9e65e63c97cd.png)

In Chrome is working well

![image](https://user-images.githubusercontent.com/37458700/218941820-77a4a8d4-db42-456a-976a-7a4619f8f62b.png)

### Affected version

Latest

### Reproduction URL

none

### How to reproduce?

Use the component into Firefox browser

### Browsers

Firefox

### Relevant log output

```Shell
No errors
```

### Additional context

In my case the workaround is set `position: unset;`  into `.tt-list` element

![image](https://user-images.githubusercontent.com/37458700/218941983-c30d1fd6-284d-4edf-b00e-a779d578514c.png)

**Comment by niketpathak** [comment]
Hello @AlonsoK28 , 

Thank you for taking the time to report this. However, nothing has changed with respect to the styles since the past 10 releases of typeahead-standalone.
I also tested the latest version of typeahead-standalone on the latest version of Firefox. Here's a screencast showing the same: 

https://user-images.githubusercontent.com/10226768/219005231-7ad7240f-bf9b-4b5e-8f16-de74c8ea5724.mp4

In your case, I think the container where you place the typeahead-standalone component has an effect i.e. overrides the styles of typeahead. So this bug is specific to your use-case. I'm closing this issue given the workaround you figured out yourself. 

Thanks! 

Good day!

**Comment by AlonsoK28** [comment]
I identified that this issue occurs always when the component `typeahead-standalone` is placed inside a [Bootstrap 5.2 lastest](https://getbootstrap.com/docs/5.2/components/offcanvas/) offcanvas

I have created a example app with this issue, follow the next steps to replicate:

1. use `firefox` browser (`chrome` works well)
2. open offcanvas using the button
3. type the word `gr` into `typeahead-input`

deployed app: https://typeahead-offcanvas-issue.vercel.app/

repo: https://github.com/AlonsoK28/typeahead-offcanvas-issue

Finally I think it would be good for your project to be able to use the component `typeahead-standalone` inside an bootstrap offcanvas component since it is a very common use case

**Comment by niketpathak** [comment]
This seems some kind of a bug with Firefox because it does not accept any value of width in percentage. However, when I set a value in pixels (or vh), it works perfectly.

Here's a screehshot: 
![image](https://user-images.githubusercontent.com/10226768/222969600-a9dd15be-a323-43b4-a7d6-43c5dee0da5b.png)

A workaround could be styling the list element (`.tt-list`) to use the width in pixels. 
In the mean time, I'm going to try to see if there exists an alternate/better solution.

**Comment by niketpathak** [comment]
@AlonsoK28 Fixed in v4.18.0. Thank you.
