### ISSUE TITLE
typeahead does not respect remote data source order

### ISSUE THREAD

**Issue by SneakyGerald** [digitalfortress-tech/typeahead-standalone#48]
### What happened?

When we use remote typeahead option to get an ordered dataset from the server by input value, seems that suggestions pop up randomly whenever the input text matches the value, however, it doesn't follow dataset order to check and print matches. For example, if we have a dataset of 50 titles that starts with "tr" ordered by name from the server and after typeahead shows suggestions the first match is not equal to the first record from the dataset. It may lead to retrieving results less relevant causing a bad user experience.

### Affected version

v4.17.0

### Reproduction URL

https://codepen.io/stevens3/pen/WNgvrMN

### How to reproduce?

1. Get a dataset with some titles ordered by the searched input value ("tr")
2. Click on the input
3. Type the text you are looking for, for example, "tr"
4. The first suggestion doesn't match the first record from the dataset

### Browsers

Chrome, Brave

**Comment by niketpathak** [comment]
Hello @SneakyGerald , Thank you for reporting this. Since typeahead is fully controlled by the trie data structure, it would be impossible to reorder the suggestions as per the order of response returned by your backend (which could also return suggestions which do not contain the input query). 

In the current version, its not possible but there is a [PR](https://github.com/digitalfortress-tech/typeahead-standalone/pull/40) in progress by [bryan-gilbert](https://github.com/bryan-gilbert) who wants something similar and I think if we let users use their own custom data source, then could order suggestions the way they want to. However, this would bypass the power of the trie data-structure and the suggestions will be completely dependant on the custom-source. 

I'm gonna put it on a priority for the next release! 
Thanks!

**Comment by SneakyGerald** [comment]
I see your point, thank you! I will check that PR.

**Comment by niketpathak** [comment]
With version [5.4.0](https://github.com/digitalfortress-tech/typeahead-standalone/releases/tag/v5.4.0), a new config parameter `hooks` is available that allows you to fully control the suggestions displayed to the user. 

Hence, closing this issue.
